Repository fortran-lang/fpm-docs, pull requests merged in 2021-12, with the labels that each got.

#13 Update main page, cleanup German translation
  locale/de/LC_MESSAGES/how-to.po
  locale/de/LC_MESSAGES/index.po
  locale/de/LC_MESSAGES/spec.po
  pages/conf.py
  pages/how-to/installation.md
  pages/index.md
Labels: i18n

#12 Initialize adding the Simplified Chinese (zh-CN) translation of the fpm documents
  Makefile
  locale/zh_CN/LC_MESSAGES/design.po
  locale/zh_CN/LC_MESSAGES/how-to.po
  locale/zh_CN/LC_MESSAGES/index.po
  locale/zh_CN/LC_MESSAGES/spec.po
  locale/zh_CN/LC_MESSAGES/sphinx.po
  locale/zh_CN/LC_MESSAGES/tutorial.po
  pages/conf.py
Labels: i18n, i18n: Chinese

#18 Add tutorial for using dependencies with fpm
  locale/de/LC_MESSAGES/tutorial.po
  pages/tutorial/dependencies.md
  pages/tutorial/index.md
  src/tutorial/dependencies/app/main.f90
  src/tutorial/dependencies/fpm.toml
  src/tutorial/dependencies/src/demo.f90
  src/tutorial/dependencies/test/main.f90
Labels: section: tutorial

#32 Cleanup translations, translate installation to German
  locale/de/LC_MESSAGES/design.po
  locale/de/LC_MESSAGES/how-to.po
  locale/de/LC_MESSAGES/index.po
  locale/de/LC_MESSAGES/spec.po
  locale/de/LC_MESSAGES/tutorial.po
  locale/es/LC_MESSAGES/design.po
  locale/es/LC_MESSAGES/how-to.po
  locale/es/LC_MESSAGES/index.po
  locale/es/LC_MESSAGES/spec.po
  locale/es/LC_MESSAGES/tutorial.po
  locale/zh_CN/LC_MESSAGES/design.po
  locale/zh_CN/LC_MESSAGES/how-to.po
  locale/zh_CN/LC_MESSAGES/index.po
  locale/zh_CN/LC_MESSAGES/spec.po
  locale/zh_CN/LC_MESSAGES/tutorial.po
Labels: i18n

#36 Add tutorial on plugins
  pages/tutorial/index.md
  pages/tutorial/plugins.md
Labels: section: tutorial
